### ISSUE TITLE
Integrate this to django signup form submit button

### ISSUE THREAD

**Issue by nawtyfellaz** [gbozee/django-paystack#11]

**Comment by nawtyfellaz** [comment]
I can not understand fully how to integrate this module into django to specify and recieve payment from users on form registration.

Please can i get an assistance?

**Comment by gbozee** [comment]
Hello, what about it didn't you understand. Did you follow the instructions and got stuck somewhere?

**Comment by nawtyfellaz** [comment]
I have 3 user signup forms which are using sessionwizard from formtools, hooking the paybutton to the forms submit button don't seem to feel right, are there other configuration to be made in place?

**Comment by nawtyfellaz** [comment]
So please if there's a way to do this so I can create subscription plans with these forms would be appreciated

**Comment by nawtyfellaz** [comment]
Please, If you may allow, I would love to mail you in person as I desire an assistance on this.

**Comment by nawtyfellaz** [comment]
I had figured it out, using JavaScript and calling the form IDs of each input needed.
