### ISSUE TITLE
Successful Payment raises a DisallowedRedirect error.

### ISSUE THREAD

**Issue by Olamyy** [gbozee/django-paystack#3]
After successful payments, the success page redirect seems to get stuck at a point and raises a 

> DisallowedRedirect at /payment/successful-verification/2ZDJZRF5VF5N/

error. 
My current paystack settings contains:
PAYSTACK_SECRET_KEY = env("PAYSTACK_SECRET_KEY", default="default_private_key")

PAYSTACK_PUBLIC_KEY = env("PAYSTACK_PUBLIC_KEY", default="default_public_key")

PAYSTACK_FAILED_URL = "dashboard:billing_failure"

PAYSTACK_SUCCESS_URL = "dashboard:billing_success"

![djangopaystack](https://user-images.githubusercontent.com/14059714/32476378-5de67b1c-c377-11e7-9fc8-0b36c1c61224.png)

**Comment by Olamyy** [comment]
Update: Fixed
Check https://github.com/Olamyy/django-paystack/pull/2

**Comment by gbozee** [comment]
Your implementation works but if you could take a look at the comments left in the PR on your branch, it would be a better solution to this.
