### ISSUE TITLE
How to track item being paid for

### ISSUE THREAD

**Issue by wofstech** [gbozee/django-paystack#4]
Good day.. i love the django-paytsack app you made, it makes it pretty easy to use paystack with django, i have just one issue. how do i know the item that's being paid for on my site. is there a provision for that in your code?

**Comment by mymi14s** [comment]
Item Id should be from your code

**Comment by gbozee** [comment]
just seeing this. you can provide the item id through the parameter `ref` in the template tag

`{% paystack_button amount=3000 email="j@example.com" ref="<your item id>" %}`

**Comment by mymi14s** [comment]
Thanks gbozee, I have both your paystack and Ravepay working Perfecto in Django 2.2. It was just a little modification + a custom webhook I wrote up.
